# Databricks Apps Configuration for Pharma Digital Twin
# Optimized for Dash application deployment

command: ["python", "app.py"]

env:
  - name: PORT
    value: "8000"
  - name: ENV
    value: "production"
  - name: PYTHONPATH
    value: "/app"

# Optional: FastAPI backend endpoint (if deployed separately)
# - name: API_BASE_URL
#   value: "http://localhost:8001/api/v1"
