# Databricks Apps Configuration
# Matches successful deployment from 2025-11-05

command: ["gunicorn", "app:server", "--bind", "0.0.0.0:8000", "--workers", "2", "--timeout", "120"]

env:
  - name: ENV
    value: "production"
  - name: PORT
    value: "8000"
  - name: DEBUG
    value: "False"
