# Databricks Apps Configuration
# For Dash application with gunicorn WSGI server

command: ["gunicorn", "--bind", "0.0.0.0:$PORT", "--workers", "2", "--timeout", "120", "--worker-class", "sync", "app:server"]

env:
  - name: DASH_DEBUG
    value: "False"
